# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [JESUS, Phizer]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username 
ko_fi: # Replace with a single Ko-fi username smithla87
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://app.asana.com/0/1149860022039400/1200028684112420','https://dl.acm.org/about/content#sec2','https://mirror.finance/#news3']
